---
- hosts: aws_ec2
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: aws_ec2
  become: true
  become_user: root
  become_method: sudo
  roles:
    - grafana